// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/9/2025, 2:48:39 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/project/Emrld/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/Emrld/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/Emrld/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/Emrld/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/Emrld/plugins/**/*.{js,ts,mjs}","/home/project/Emrld/composables/**/*.{js,ts,mjs}","/home/project/Emrld/utils/**/*.{js,ts,mjs}","/home/project/Emrld/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/Emrld/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/project/Emrld/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/project/Emrld/app.config.{js,ts,mjs}","/home/project/Emrld/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;